### ISSUE TITLE
macOS GraalVM Github Action build is broken

### ISSUE THREAD

**Issue by msgilligan** [SupernautApp/supernaut-fx-sample-maven#9]
My guess is this was caused by the upgraded Gluon FX Plugin.

The macOS build works on my laptop because I have the Apple developer certificate there.

Error message:
```
java.lang.RuntimeException: No valid Identity (Certificate) found for macOS development.
13800
[INFO] ------------------------------------------------------------------------
13801
Please check https://docs.gluonhq.com/ for more information.
13802
[INFO] BUILD FAILURE
13803
	at com.gluonhq.substrate.util.macos.CodeSigning.assertValidIdentity(CodeSigning.java:137)
13804
[INFO] ------------------------------------------------------------------------
13805
	at com.gluonhq.substrate.util.macos.CodeSigning.signApp(CodeSigning.java:103)
13806
	at com.gluonhq.substrate.target.MacOSTargetConfiguration.createAppBundle(MacOSTargetConfiguration.java:173)
13807
[INFO] Total time:  07:06 min
13808
	at com.gluonhq.substrate.target.MacOSTargetConfiguration.packageApp(MacOSTargetConfiguration.java:146)
13809
[INFO] Finished at: 2022-01-05T22:08:22Z
13810
	at com.gluonhq.substrate.SubstrateDispatcher.nativePackage(SubstrateDispatcher.java:460)
13811
[INFO] ------------------------------------------------------------------------
13812
	at com.gluonhq.NativePackageMojo.execute(NativePackageMojo.java:48)
13813
Error:  Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.10:package (default-cli) on project hellofx: Error: No valid Identity (Certificate) found for macOS development.
13814
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
13815
Error:  Please check https://docs.gluonhq.com/ for more information.
13816
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
13817
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
13818
Error:  -> [Help 1]
13819
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
13820
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
13821
Error:  
13822
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
13823
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
13824
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
13825
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
13826
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
13827
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
13828
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:972)
13829
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:293)
13830
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:196)
13831
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
13832
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
13833
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
13834
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
13835
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
13836
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
13837
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
13838
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
13839
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
13840
Error:  Re-run Maven using the -X switch to enable full debug logging.
13841
Error:  
13842
Error:  For more information about the errors and possible solutions, please read the following articles:
13843
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
13844
Error: Process completed with exit code 1.
```

**Comment by msgilligan** [comment]
Fixed (or worked-around, I suppose) by 60cc59d412c6c75ea7eece13e1d86d6779ff4df3
